import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container} style={{ fontFamily: "Poppins" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Shazam Carai</h1>

      <p className={styles.description}>
        <img src="imgs/tobey.jpg" alt="" />
        <br />
        <p style={{ fontSize: "12px", fontWeight: "600" }}>
          Por: Gustavo Pazeto
        </p>
      </p>
    </div>
  );
}
